package ClientAndServer;


/**
* ClientAndServer/alarmListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 4 April 2017 15:10:12 o'clock BST
*/

public final class alarmListHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientAndServer.AlarmLogs value[] = null;

  public alarmListHolder ()
  {
  }

  public alarmListHolder (ClientAndServer.AlarmLogs[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientAndServer.alarmListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientAndServer.alarmListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientAndServer.alarmListHelper.type ();
  }

}
