package ClientAndServer;

/**
* ClientAndServer/AlarmLogsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 5 April 2017 11:35:44 o'clock BST
*/

public final class AlarmLogsHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientAndServer.AlarmLogs value = null;

  public AlarmLogsHolder ()
  {
  }

  public AlarmLogsHolder (ClientAndServer.AlarmLogs initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientAndServer.AlarmLogsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientAndServer.AlarmLogsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientAndServer.AlarmLogsHelper.type ();
  }

}
