package ClientAndServer;


/**
* ClientAndServer/ClientSensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 4 April 2017 17:51:10 o'clock BST
*/

public interface ClientSensorOperations 
{
  void sendSensorPanicMessage (String sensorID, String roomName);
} // interface ClientSensorOperations
