package ClientAndServer;


/**
* ClientAndServer/ClientSensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 6 April 2017 23:57:23 o'clock BST
*/

public interface ClientSensorOperations 
{
  void sendSensorPanicMessage (String sensorID, String roomName);
} // interface ClientSensorOperations
