package ClientAndServer;


/**
* ClientAndServer/ClientServerHomeHubPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 6 April 2017 23:57:23 o'clock BST
*/

public abstract class ClientServerHomeHubPOA extends org.omg.PortableServer.Servant
 implements ClientAndServer.ClientServerHomeHubOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("switchOn", new java.lang.Integer (0));
    _methods.put ("switchOff", new java.lang.Integer (1));
    _methods.put ("sendSensorPanicMessage", new java.lang.Integer (2));
    _methods.put ("sendPanicMessage", new java.lang.Integer (3));
    _methods.put ("sendOkayMessage", new java.lang.Integer (4));
    _methods.put ("notifyServer", new java.lang.Integer (5));
    _methods.put ("setConnection", new java.lang.Integer (6));
    _methods.put ("resetCamera", new java.lang.Integer (7));
    _methods.put ("setCamConnection", new java.lang.Integer (8));
    _methods.put ("getCameraStatus", new java.lang.Integer (9));
    _methods.put ("sendCameraStatus", new java.lang.Integer (10));
    _methods.put ("log", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientAndServer/ClientServerHomeHub/switchOn
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOn (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ClientAndServer/ClientServerHomeHub/switchOff
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOff (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ClientAndServer/ClientServerHomeHub/sendSensorPanicMessage
       {
         String sensorID = in.read_string ();
         String roomName = in.read_string ();
         this.sendSensorPanicMessage (sensorID, roomName);
         out = $rh.createReply();
         break;
       }

       case 3:  // ClientAndServer/ClientServerHomeHub/sendPanicMessage
       {
         String camID = in.read_string ();
         String roomName = in.read_string ();
         String $result = null;
         $result = this.sendPanicMessage (camID, roomName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ClientAndServer/ClientServerHomeHub/sendOkayMessage
       {
         String camID = in.read_string ();
         this.sendOkayMessage (camID);
         out = $rh.createReply();
         break;
       }

       case 5:  // ClientAndServer/ClientServerHomeHub/notifyServer
       {
         String camID = in.read_string ();
         String homeHubName = in.read_string ();
         String contact = in.read_string ();
         String $result = null;
         $result = this.notifyServer (camID, homeHubName, contact);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ClientAndServer/ClientServerHomeHub/setConnection
       {
         String name = in.read_string ();
         this.setConnection (name);
         out = $rh.createReply();
         break;
       }

       case 7:  // ClientAndServer/ClientServerHomeHub/resetCamera
       {
         String c = in.read_string ();
         this.resetCamera (c);
         out = $rh.createReply();
         break;
       }

       case 8:  // ClientAndServer/ClientServerHomeHub/setCamConnection
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.setCamConnection (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // ClientAndServer/ClientServerHomeHub/getCameraStatus
       {
         String camID = in.read_string ();
         this.getCameraStatus (camID);
         out = $rh.createReply();
         break;
       }

       case 10:  // ClientAndServer/ClientServerHomeHub/sendCameraStatus
       {
         String camID = in.read_string ();
         String status = in.read_string ();
         this.sendCameraStatus (camID, status);
         out = $rh.createReply();
         break;
       }

       case 11:  // ClientAndServer/ClientServerHomeHub/log
       {
         String $result[] = null;
         $result = this.log ();
         out = $rh.createReply();
         ClientAndServer.logsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientAndServer/ClientServerHomeHub:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientServerHomeHub _this() 
  {
    return ClientServerHomeHubHelper.narrow(
    super._this_object());
  }

  public ClientServerHomeHub _this(org.omg.CORBA.ORB orb) 
  {
    return ClientServerHomeHubHelper.narrow(
    super._this_object(orb));
  }


} // class ClientServerHomeHubPOA
