package ClientAndServer;


/**
* ClientAndServer/ClientServerHomeHubHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 6 April 2017 23:57:23 o'clock BST
*/

abstract public class ClientServerHomeHubHelper
{
  private static String  _id = "IDL:ClientAndServer/ClientServerHomeHub:1.0";

  public static void insert (org.omg.CORBA.Any a, ClientAndServer.ClientServerHomeHub that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClientAndServer.ClientServerHomeHub extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ClientAndServer.ClientServerHomeHubHelper.id (), "ClientServerHomeHub");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClientAndServer.ClientServerHomeHub read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientServerHomeHubStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClientAndServer.ClientServerHomeHub value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ClientAndServer.ClientServerHomeHub narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientAndServer.ClientServerHomeHub)
      return (ClientAndServer.ClientServerHomeHub)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClientAndServer._ClientServerHomeHubStub stub = new ClientAndServer._ClientServerHomeHubStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ClientAndServer.ClientServerHomeHub unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientAndServer.ClientServerHomeHub)
      return (ClientAndServer.ClientServerHomeHub)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClientAndServer._ClientServerHomeHubStub stub = new ClientAndServer._ClientServerHomeHubStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
