package ClientAndServer;


/**
* ClientAndServer/ClientServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 22 March 2017 14:00:55 o'clock GMT
*/

public interface ClientServant extends ClientServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientServant
