package ClientAndServer;


/**
* ClientAndServer/ClientCamera.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 5 April 2017 17:15:29 o'clock BST
*/

public interface ClientCamera extends ClientCameraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientCamera
