package ClientAndServer;


/**
* ClientAndServer/ClientServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 22 March 2017 14:00:55 o'clock GMT
*/

public interface ClientServantOperations 
{
} // interface ClientServantOperations
