package ClientAndServer;


/**
* ClientAndServer/ClientCameraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 4 April 2017 15:10:12 o'clock BST
*/

public interface ClientCameraOperations 
{
  void switchOn (String camID);
  void switchOff (String camID);
  void sendPanicMessage (String camID);
  void sendOkayMessage (String camID);
  void setCamServer (String camID);
  void resetCamStatus ();
  ClientAndServer.Image currentImage ();
  void getCameraStatus (String camID);
} // interface ClientCameraOperations
