package ClientAndServer;


/**
* ClientAndServer/ClientCameraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 6 April 2017 23:57:23 o'clock BST
*/

public interface ClientCameraOperations 
{
  void switchOn (String camID);
  void switchOff (String camID);
  void sendPanicMessage (String camID);
  void sendOkayMessage (String camID);
  void setCamServer (String camID);
  void resetCamStatus ();
  String itemName ();
  String roomName ();
  ClientAndServer.Image currentImage ();
  void getCameraStatus (String camID);
} // interface ClientCameraOperations
