package ClientAndServer;


/**
* ClientAndServer/ClientSensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 6 April 2017 23:57:23 o'clock BST
*/

public interface ClientSensor extends ClientSensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientSensor
