package ClientAndServer;


/**
* ClientAndServer/ClientSensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Friday, 31 March 2017 15:48:30 o'clock BST
*/

public interface ClientSensorOperations 
{
  void sendSensorPanicMessage (String sensorID, String roomName);
} // interface ClientSensorOperations
