package ClientAndServer;

/**
* ClientAndServer/ClientServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 22 March 2017 14:00:55 o'clock GMT
*/

public final class ClientServantHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientAndServer.ClientServant value = null;

  public ClientServantHolder ()
  {
  }

  public ClientServantHolder (ClientAndServer.ClientServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientAndServer.ClientServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientAndServer.ClientServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientAndServer.ClientServantHelper.type ();
  }

}
