package ClientAndServer;


/**
* ClientAndServer/ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 23 March 2017 15:50:52 o'clock GMT
*/

public interface ClientOperations 
{
  void switchOn (String camID);
  void switchOff (String camID);
  void sendPanicMessage (String camID);
  void setCamServer (String camID);
  void resetCamStatus ();
} // interface ClientOperations
