package ClientAndServer;


/**
* ClientAndServer/ClientServerHomeHub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 4 April 2017 15:10:12 o'clock BST
*/

public interface ClientServerHomeHub extends ClientServerHomeHubOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientServerHomeHub
