package ClientAndServer;


/**
* ClientAndServer/HelloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 23 March 2017 15:50:52 o'clock GMT
*/

public interface HelloWorldOperations 
{
  String hello_world ();
  String panicServer (String camID);
  String switchOn (String camID);
  String switchOff (String camID);
  void showCamStatus (String messageStatus);
  String connection (String name);
  void resetSensor (String CamID);
} // interface HelloWorldOperations
