package ClientAndServer;


/**
* ClientAndServer/HelloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 21 March 2017 15:42:42 o'clock GMT
*/

public interface HelloWorldOperations 
{
  String hello_world ();
  String panicServer (String camID);
  String switchOn (String camID);
  String switchOff (String camID);
  void showCamStatus (String messageStatus);
  void resetSensor ();
} // interface HelloWorldOperations
