package ClientAndServer;


/**
* ClientAndServer/HelloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 29 March 2017 16:23:14 o'clock BST
*/

public interface HelloWorldOperations 
{
  String hello_world ();
  String panicServer (String camID);
  void sensorPanicServer (String sensorID);
  String switchOn (String camID);
  String switchOff (String camID);
  void showCamStatus (String messageStatus);
  void showSensorStatus (String messageStatus);
  String connection (String name);
  void resetSensor (String CamID, String homeHubName);
  void showOkayMessage (String camID, String homeHubName);
  void getStatus (String camID, String homeHubName);
  void showCameraStatus (String camID, String status);
} // interface HelloWorldOperations
