package ClientAndServer;


/**
* ClientAndServer/HelloWorldPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Friday, 17 March 2017 17:22:55 o'clock GMT
*/

public abstract class HelloWorldPOA extends org.omg.PortableServer.Servant
 implements ClientAndServer.HelloWorldOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("hello_world", new java.lang.Integer (0));
    _methods.put ("panicServer", new java.lang.Integer (1));
    _methods.put ("switchOn", new java.lang.Integer (2));
    _methods.put ("switchOff", new java.lang.Integer (3));
    _methods.put ("showCamStatus", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientAndServer/HelloWorld/hello_world
       {
         String $result = null;
         $result = this.hello_world ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ClientAndServer/HelloWorld/panicServer
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.panicServer (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ClientAndServer/HelloWorld/switchOn
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOn (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ClientAndServer/HelloWorld/switchOff
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOff (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ClientAndServer/HelloWorld/showCamStatus
       {
         String messageStatus = in.read_string ();
         this.showCamStatus (messageStatus);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientAndServer/HelloWorld:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HelloWorld _this() 
  {
    return HelloWorldHelper.narrow(
    super._this_object());
  }

  public HelloWorld _this(org.omg.CORBA.ORB orb) 
  {
    return HelloWorldHelper.narrow(
    super._this_object(orb));
  }


} // class HelloWorldPOA
