package ClientAndServer;

/**
* ClientAndServer/HomehubHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 8 March 2017 14:29:25 o'clock GMT
*/

public final class HomehubHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientAndServer.Homehub value = null;

  public HomehubHolder ()
  {
  }

  public HomehubHolder (ClientAndServer.Homehub initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientAndServer.HomehubHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientAndServer.HomehubHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientAndServer.HomehubHelper.type ();
  }

}
