package ClientAndServer;


/**
* ClientAndServer/HomehubPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 8 March 2017 14:29:25 o'clock GMT
*/

public abstract class HomehubPOA extends org.omg.PortableServer.Servant
 implements ClientAndServer.HomehubOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fetch_message", new java.lang.Integer (0));
    _methods.put ("sendPanicMessage", new java.lang.Integer (1));
    _methods.put ("notifyServer", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientAndServer/Homehub/fetch_message
       {
         String $result = null;
         $result = this.fetch_message ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ClientAndServer/Homehub/sendPanicMessage
       {
         String $result = null;
         $result = this.sendPanicMessage ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ClientAndServer/Homehub/notifyServer
       {
         String $result = null;
         $result = this.notifyServer ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientAndServer/Homehub:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Homehub _this() 
  {
    return HomehubHelper.narrow(
    super._this_object());
  }

  public Homehub _this(org.omg.CORBA.ORB orb) 
  {
    return HomehubHelper.narrow(
    super._this_object(orb));
  }


} // class HomehubPOA
