package ClientAndServer;


/**
* ClientAndServer/HomeHubObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Friday, 31 March 2017 15:01:57 o'clock BST
*/

public final class HomeHubObject implements org.omg.CORBA.portable.IDLEntity
{
  public String camID = null;
  public String name = null;

  public HomeHubObject ()
  {
  } // ctor

  public HomeHubObject (String _camID, String _name)
  {
    camID = _camID;
    name = _name;
  } // ctor

} // class HomeHubObject
