package ClientAndServer;


/**
* ClientAndServer/Homehub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 8 March 2017 14:29:25 o'clock GMT
*/

public interface Homehub extends HomehubOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Homehub
