package ClientAndServer;


/**
* ClientAndServer/homeHubListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Sunday, 26 March 2017 15:19:18 o'clock BST
*/

public final class homeHubListHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientAndServer.HomeHubObject value[] = null;

  public homeHubListHolder ()
  {
  }

  public homeHubListHolder (ClientAndServer.HomeHubObject[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientAndServer.homeHubListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientAndServer.homeHubListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientAndServer.homeHubListHelper.type ();
  }

}
