package ClientAndServer;


/**
* ClientAndServer/HomehubOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 8 March 2017 14:29:25 o'clock GMT
*/

public interface HomehubOperations 
{
  String fetch_message ();
  String sendPanicMessage ();
  String notifyServer ();
} // interface HomehubOperations
