package ClientAndServer;


/**
* ClientAndServer/ImageHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 4 April 2017 17:51:10 o'clock BST
*/

abstract public class ImageHelper
{
  private static String  _id = "IDL:ClientAndServer/Image:1.0";

  public static void insert (org.omg.CORBA.Any a, ClientAndServer.Image that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClientAndServer.Image extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "time",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "date",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "status",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ClientAndServer.ImageHelper.id (), "Image", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClientAndServer.Image read (org.omg.CORBA.portable.InputStream istream)
  {
    ClientAndServer.Image value = new ClientAndServer.Image ();
    value.time = istream.read_string ();
    value.date = istream.read_string ();
    value.status = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClientAndServer.Image value)
  {
    ostream.write_string (value.time);
    ostream.write_string (value.date);
    ostream.write_string (value.status);
  }

}
