package ClientAndServer;


/**
* ClientAndServer/RelayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Sunday, 26 March 2017 15:19:18 o'clock BST
*/

public interface RelayOperations 
{
  ClientAndServer.HomeHubObject[] hHist ();
  String switchOn (String camID);
  String switchOff (String camID);
  String fetch_message ();
  String sendPanicMessage (String camID);
  void sendOkayMessage (String camID);
  String notifyServer (String camID);
  void setConnection (String name);
  void resetCamera (String c);
  String setCamConnection (String name);
  void addHomeHub (String homeHubName);
  void getCameraStatus (String camID);
  void sendCameraStatus (String camID, String status);
} // interface RelayOperations
