package ClientAndServer;


/**
* ClientAndServer/RelayPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Sunday, 26 March 2017 15:19:18 o'clock BST
*/

public abstract class RelayPOA extends org.omg.PortableServer.Servant
 implements ClientAndServer.RelayOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_hHist", new java.lang.Integer (0));
    _methods.put ("switchOn", new java.lang.Integer (1));
    _methods.put ("switchOff", new java.lang.Integer (2));
    _methods.put ("fetch_message", new java.lang.Integer (3));
    _methods.put ("sendPanicMessage", new java.lang.Integer (4));
    _methods.put ("sendOkayMessage", new java.lang.Integer (5));
    _methods.put ("notifyServer", new java.lang.Integer (6));
    _methods.put ("setConnection", new java.lang.Integer (7));
    _methods.put ("resetCamera", new java.lang.Integer (8));
    _methods.put ("setCamConnection", new java.lang.Integer (9));
    _methods.put ("addHomeHub", new java.lang.Integer (10));
    _methods.put ("getCameraStatus", new java.lang.Integer (11));
    _methods.put ("sendCameraStatus", new java.lang.Integer (12));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientAndServer/Relay/_get_hHist
       {
         ClientAndServer.HomeHubObject $result[] = null;
         $result = this.hHist ();
         out = $rh.createReply();
         ClientAndServer.homeHubListHelper.write (out, $result);
         break;
       }

       case 1:  // ClientAndServer/Relay/switchOn
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOn (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ClientAndServer/Relay/switchOff
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOff (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ClientAndServer/Relay/fetch_message
       {
         String $result = null;
         $result = this.fetch_message ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ClientAndServer/Relay/sendPanicMessage
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.sendPanicMessage (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ClientAndServer/Relay/sendOkayMessage
       {
         String camID = in.read_string ();
         this.sendOkayMessage (camID);
         out = $rh.createReply();
         break;
       }

       case 6:  // ClientAndServer/Relay/notifyServer
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.notifyServer (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // ClientAndServer/Relay/setConnection
       {
         String name = in.read_string ();
         this.setConnection (name);
         out = $rh.createReply();
         break;
       }

       case 8:  // ClientAndServer/Relay/resetCamera
       {
         String c = in.read_string ();
         this.resetCamera (c);
         out = $rh.createReply();
         break;
       }

       case 9:  // ClientAndServer/Relay/setCamConnection
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.setCamConnection (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // ClientAndServer/Relay/addHomeHub
       {
         String homeHubName = in.read_string ();
         this.addHomeHub (homeHubName);
         out = $rh.createReply();
         break;
       }

       case 11:  // ClientAndServer/Relay/getCameraStatus
       {
         String camID = in.read_string ();
         this.getCameraStatus (camID);
         out = $rh.createReply();
         break;
       }

       case 12:  // ClientAndServer/Relay/sendCameraStatus
       {
         String camID = in.read_string ();
         String status = in.read_string ();
         this.sendCameraStatus (camID, status);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientAndServer/Relay:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Relay _this() 
  {
    return RelayHelper.narrow(
    super._this_object());
  }

  public Relay _this(org.omg.CORBA.ORB orb) 
  {
    return RelayHelper.narrow(
    super._this_object(orb));
  }


} // class RelayPOA
