package ClientAndServer;


/**
* ClientAndServer/RelayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 23 March 2017 15:00:59 o'clock GMT
*/

public interface RelayOperations 
{
  String switchOn (String camID);
  String switchOff (String camID);
  String fetch_message ();
  String sendPanicMessage (String camID);
  String notifyServer (String camID);
  void setConnection (String name);
  void resetCamera ();
  String setCamConnection (String name);
} // interface RelayOperations
