package ClientAndServer;


/**
* ClientAndServer/ServerRegionalOfficePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 4 April 2017 15:10:12 o'clock BST
*/

public abstract class ServerRegionalOfficePOA extends org.omg.PortableServer.Servant
 implements ClientAndServer.ServerRegionalOfficeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_list", new java.lang.Integer (0));
    _methods.put ("hello_world", new java.lang.Integer (1));
    _methods.put ("panicServer", new java.lang.Integer (2));
    _methods.put ("sensorPanicServer", new java.lang.Integer (3));
    _methods.put ("switchOn", new java.lang.Integer (4));
    _methods.put ("switchOff", new java.lang.Integer (5));
    _methods.put ("showCamStatus", new java.lang.Integer (6));
    _methods.put ("showSensorStatus", new java.lang.Integer (7));
    _methods.put ("connection", new java.lang.Integer (8));
    _methods.put ("resetSensor", new java.lang.Integer (9));
    _methods.put ("showOkayMessage", new java.lang.Integer (10));
    _methods.put ("getStatus", new java.lang.Integer (11));
    _methods.put ("showCameraStatus", new java.lang.Integer (12));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientAndServer/ServerRegionalOffice/_get_list
       {
         ClientAndServer.AlarmLogs $result[] = null;
         $result = this.list ();
         out = $rh.createReply();
         ClientAndServer.alarmListHelper.write (out, $result);
         break;
       }

       case 1:  // ClientAndServer/ServerRegionalOffice/hello_world
       {
         String $result = null;
         $result = this.hello_world ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ClientAndServer/ServerRegionalOffice/panicServer
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.panicServer (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ClientAndServer/ServerRegionalOffice/sensorPanicServer
       {
         String sensorID = in.read_string ();
         String roomName = in.read_string ();
         this.sensorPanicServer (sensorID, roomName);
         out = $rh.createReply();
         break;
       }

       case 4:  // ClientAndServer/ServerRegionalOffice/switchOn
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOn (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ClientAndServer/ServerRegionalOffice/switchOff
       {
         String camID = in.read_string ();
         String $result = null;
         $result = this.switchOff (camID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ClientAndServer/ServerRegionalOffice/showCamStatus
       {
         String messageStatus = in.read_string ();
         this.showCamStatus (messageStatus);
         out = $rh.createReply();
         break;
       }

       case 7:  // ClientAndServer/ServerRegionalOffice/showSensorStatus
       {
         String messageStatus = in.read_string ();
         this.showSensorStatus (messageStatus);
         out = $rh.createReply();
         break;
       }

       case 8:  // ClientAndServer/ServerRegionalOffice/connection
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.connection (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // ClientAndServer/ServerRegionalOffice/resetSensor
       {
         String CamID = in.read_string ();
         String homeHubName = in.read_string ();
         this.resetSensor (CamID, homeHubName);
         out = $rh.createReply();
         break;
       }

       case 10:  // ClientAndServer/ServerRegionalOffice/showOkayMessage
       {
         String camID = in.read_string ();
         String homeHubName = in.read_string ();
         this.showOkayMessage (camID, homeHubName);
         out = $rh.createReply();
         break;
       }

       case 11:  // ClientAndServer/ServerRegionalOffice/getStatus
       {
         String camID = in.read_string ();
         String homeHubName = in.read_string ();
         this.getStatus (camID, homeHubName);
         out = $rh.createReply();
         break;
       }

       case 12:  // ClientAndServer/ServerRegionalOffice/showCameraStatus
       {
         String camID = in.read_string ();
         String status = in.read_string ();
         this.showCameraStatus (camID, status);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientAndServer/ServerRegionalOffice:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerRegionalOffice _this() 
  {
    return ServerRegionalOfficeHelper.narrow(
    super._this_object());
  }

  public ServerRegionalOffice _this(org.omg.CORBA.ORB orb) 
  {
    return ServerRegionalOfficeHelper.narrow(
    super._this_object(orb));
  }


} // class ServerRegionalOfficePOA
