package ClientAndServer;


/**
* ClientAndServer/ServerRegionalOffice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Tuesday, 4 April 2017 17:51:10 o'clock BST
*/

public interface ServerRegionalOffice extends ServerRegionalOfficeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerRegionalOffice
