package ClientAndServer;


/**
* ClientAndServer/ServerRegionalOffice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Wednesday, 5 April 2017 22:14:33 o'clock BST
*/

public interface ServerRegionalOffice extends ServerRegionalOfficeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerRegionalOffice
