package ClientAndServer;

/**
* ClientAndServer/ServerRegionalOfficeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 6 April 2017 23:57:23 o'clock BST
*/

public final class ServerRegionalOfficeHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientAndServer.ServerRegionalOffice value = null;

  public ServerRegionalOfficeHolder ()
  {
  }

  public ServerRegionalOfficeHolder (ClientAndServer.ServerRegionalOffice initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientAndServer.ServerRegionalOfficeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientAndServer.ServerRegionalOfficeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientAndServer.ServerRegionalOfficeHelper.type ();
  }

}
