// Example of a "relay" - a client and server.
// Uses the old favourite Hello World as a basis.

module ClientAndServer {
    interface Relay {
    string switchOn(in string camID);
    string switchOff(in string camID);
    string fetch_message();
	string sendPanicMessage(in string camID);
	string notifyServer(in string camID);
	void resetCamera();
    };

    interface HelloWorld {
	string hello_world();
	string panicServer(in string camID);
	string switchOn(in string camID);
	string switchOff(in string camID);
	void showCamStatus(in string messageStatus);
	void resetSensor();
    };			
};
