// Example of a "relay" - a client and server.
// Uses the old favourite Hello World as a basis.

module ClientAndServer {

	typedef sequence <string> logs;
	
	struct Image{
	string time;
	string  date;
	string status;
	};
	
	interface ClientCamera{
	void switchOn(in string camID);
	void switchOff(in string camID);
	void sendPanicMessage(in string camID);
	void sendOkayMessage(in string camID);
	void setCamServer(in string camID);
	void resetCamStatus();
	string itemName();
	string roomName();
	Image currentImage();
	void getCameraStatus(in string camID);
	};
	
	interface ClientSensor{
	void sendSensorPanicMessage(in string sensorID, in string roomName);
	};
	
    interface ClientServerHomeHub {
    string switchOn(in string camID);
    string switchOff(in string camID);
    void sendSensorPanicMessage(in string sensorID, in string roomName);
	string sendPanicMessage(in string camID, in string roomName);
	void sendOkayMessage(in string camID);
	string notifyServer(in string camID, in string homeHubName, in string contact);
	void setConnection(in string name);
	void resetCamera(in string c);
	string setCamConnection(in string name);
	void getCameraStatus(in string camID);
	void sendCameraStatus(in string camID, in string status);
	logs log(); 
    };

    interface ServerRegionalOffice {
	string panicServer(in string camID , in string homeHubName, in string contact);
	void sensorPanicServer(in string sensorID, in string roomName);
	string switchOn(in string camID);
	string switchOff(in string camID);
	void showCamStatus(in string messageStatus);
	void showSensorStatus(in string messageStatus);
	string connection(in string name);
	void resetSensor(in string CamID, in string homeHubName);
	void showOkayMessage(in string camID, in string homeHubName);
	void getStatus(in string camID, in string homeHubName);
	void showCameraStatus(in string camID, in string status);
	void getLog (in string homeHubName);
    };			
};
